from __future__ import annotations

from datetime import datetime
from typing import Iterable

from .models import RepoSnapshot, WorkItem


TEXT = {
    "en": {
        "title": "OSS Careboard",
        "summary": "Repository summary",
        "metric": "Metric",
        "value": "Value",
        "stars": "Stars",
        "forks": "Forks",
        "subscribers": "Subscribers",
        "open_issues": "Open issues analyzed",
        "open_prs": "Open pull requests analyzed",
        "stale_issues": "Issues needing attention",
        "stale_prs": "Pull requests needing attention",
        "release": "Release freshness",
        "latest_release": "Latest release",
        "no_release": "No published GitHub release",
        "last_push": "Last push",
        "days_ago": "{days} days ago",
        "none": "Nothing in this queue.",
        "idle": "idle {days}d",
        "age": "open {days}d",
        "draft": "draft",
        "archived": "This repository is archived.",
        "generated": "Generated by OSS Careboard at {time}.",
    },
    "zh": {
        "title": "开源维护看板",
        "summary": "仓库概览",
        "metric": "指标",
        "value": "数值",
        "stars": "Stars",
        "forks": "Forks",
        "subscribers": "订阅者",
        "open_issues": "已分析的未关闭 Issue",
        "open_prs": "已分析的未合并 PR",
        "stale_issues": "需要关注的 Issue",
        "stale_prs": "需要关注的 PR",
        "release": "发布新鲜度",
        "latest_release": "最近发布",
        "no_release": "尚未发布 GitHub Release",
        "last_push": "最近推送",
        "days_ago": "{days} 天前",
        "none": "此队列暂无项目。",
        "idle": "闲置 {days} 天",
        "age": "已开启 {days} 天",
        "draft": "草稿",
        "archived": "此仓库已归档。",
        "generated": "OSS Careboard 生成于 {time}。",
    },
}


def _days_since(value: datetime | None, now: datetime) -> int | None:
    if value is None:
        return None
    return max(0, (now - value).days)


def _escape_table(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _item_lines(
    items: Iterable[WorkItem], now: datetime, text: dict[str, str], limit: int
) -> list[str]:
    selected = list(items)[:limit]
    if not selected:
        return [text["none"]]

    lines: list[str] = []
    for item in selected:
        details = [
            text["idle"].format(days=item.idle_days(now)),
            text["age"].format(days=item.age_days(now)),
        ]
        if item.draft:
            details.append(text["draft"])
        if item.labels:
            details.append(", ".join(f"`{label}`" for label in item.labels[:4]))
        lines.append(
            f"- [#{item.number} {_escape_table(item.title)}]({item.html_url}) "
            f"({'; '.join(details)})"
        )
    return lines


def render_markdown(
    snapshot: RepoSnapshot,
    stale_days: int = 30,
    limit: int = 10,
    language: str = "en",
) -> str:
    if language not in TEXT:
        raise ValueError(f"unsupported language: {language}")
    if stale_days < 0:
        raise ValueError("stale_days must be zero or greater")
    if limit < 1:
        raise ValueError("limit must be at least one")

    text = TEXT[language]
    now = snapshot.fetched_at
    stale_issues = sorted(
        (item for item in snapshot.issues if item.idle_days(now) >= stale_days),
        key=lambda item: item.updated_at,
    )
    stale_prs = sorted(
        (item for item in snapshot.pull_requests if item.idle_days(now) >= stale_days),
        key=lambda item: item.updated_at,
    )

    release_days = _days_since(snapshot.latest_release_published_at, now)
    push_days = _days_since(snapshot.pushed_at, now)
    if snapshot.latest_release_name and snapshot.latest_release_url:
        release_value = (
            f"[{snapshot.latest_release_name}]({snapshot.latest_release_url})"
            + (
                f" ({text['days_ago'].format(days=release_days)})"
                if release_days is not None
                else ""
            )
        )
    else:
        release_value = text["no_release"]

    lines = [
        f"# {text['title']}: [{snapshot.repository}]({snapshot.html_url})",
        "",
    ]
    if snapshot.description:
        lines.extend([snapshot.description, ""])
    if snapshot.archived:
        lines.extend([f"> **{text['archived']}**", ""])
    lines.extend(
        [
            f"## {text['summary']}",
            "",
            f"| {text['metric']} | {text['value']} |",
            "| --- | ---: |",
            f"| {text['stars']} | {snapshot.stars} |",
            f"| {text['forks']} | {snapshot.forks} |",
            f"| {text['subscribers']} | {snapshot.subscribers} |",
            f"| {text['open_issues']} | {len(snapshot.issues)} |",
            f"| {text['open_prs']} | {len(snapshot.pull_requests)} |",
            "",
            f"## {text['stale_prs']} ({len(stale_prs)})",
            "",
            *_item_lines(stale_prs, now, text, limit),
            "",
            f"## {text['stale_issues']} ({len(stale_issues)})",
            "",
            *_item_lines(stale_issues, now, text, limit),
            "",
            f"## {text['release']}",
            "",
            f"- **{text['latest_release']}:** {release_value}",
            f"- **{text['last_push']}:** "
            + (
                text["days_ago"].format(days=push_days)
                if push_days is not None
                else "unknown"
            ),
            "",
            "---",
            text["generated"].format(time=now.isoformat()),
            "",
        ]
    )
    return "\n".join(lines)
